### PR TITLE
Add documentation examples

### PR DESCRIPTION
**Pull request by adamkvitek**

### CODE REVIEW

**Review by ievans — APPROVED** [review]

**Comment by ievans** [comment]
@adamkvitek these look great. can you add some examples of how to run them to the README?

**Comment by adamkvitek** [comment]
@ievans just the simple commands? This code is here to accompany documentation ([now in this draft](https://docs.google.com/document/d/1EbZra3oMMei5foK0b2b40g-djS3Z6OsPfQtgyAYKC2w/edit#)), so maybe a link to the docs in the README will suffice? :-) Do not want to double the text sources.

**Comment by ievans** [comment]
Simple commands would be good I think

**Comment by adamkvitek** [comment]
@ievans done! I am still not including many commands, will rather lead people to our docs page. Just trying to avoid having us to update the same information on two pages. https://github.com/returntocorp/semgrep-docs/pull/532

**Pull request merged**
